name: 云服务器CICD
# 监听 main 分支上的 push 事件
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 安装依赖
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 使用VitePress构建
        run: pnpm docs:build

      # 清空目标服务器上的目录内容
      - name: 清空目标服务器该文件夹下内容
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf /nwa/nginx/html/myvue/*

      # 部署到服务器
      - name: 上传打包后的资源到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: "/nwa/nginx/html/myvue"
          strip_components: 1
