name: 打包文件并推送到云服务器
# 监听 main 分支上的 push 事件
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 安装依赖
        run: yarn install

      - name: 使用VitePress构建
        run: yarn docs:build

      # 列出构建输出目录内容
      - name: 列出构建输出目录内容
        run: ls -la ./docs/.vitepress/dist

      # 列出构建输出目录内容（包含子目录和文件）
      - name: 列出构建输出目录内容（详细）
        run: find ./docs/.vitepress/dist -type f

      # 清空目标服务器上的目录内容
      - name: 清空目标服务器该文件夹下内容
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf /nwa/nginx91/html/myvue/*

      # 部署到服务器
      - name: 上传打包后的资源到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ./docs/* ./docs/.vitepress/* # 修改此行以包含 .vitepress 目录下的文件
          target: /nwa/nginx91/html/myvue/
          strip_components: 1

      # 列出服务器目录内容
      - name: 列出服务器目录内容
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -la /nwa/nginx91/html/myvue
